test:
	perl ./scripts/test_printp.pl
	perl ./scripts/test_dict2tri.pl
	perl ./scripts/test_prunetree.pl

clean:
	rm -f dict2tri.no_triphones
	rm -f dict2tri.triphones
	rm -f printp.mean.txt
	rm -f printp.mixw.txt
	rm -f printp.tmat.txt
	rm -f printp.var.txt