#!/bin/csh
# ====================================================================
# Copyright (c) 2000 Carnegie Mellon University.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer. 
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# 3. The names "Sphinx" and "Carnegie Mellon" must not be used to
#    endorse or promote products derived from this software without
#    prior written permission. To obtain permission, contact 
#    sphinx@cs.cmu.edu.
#
# 4. Products derived from this software may not be called "Sphinx"
#    nor may "Sphinx" appear in their names without prior written
#    permission of Carnegie Mellon University. To obtain permission,
#    contact sphinx@cs.cmu.edu.
#
# 5. Redistributions of any form whatsoever must retain the following
#    acknowledgment:
#    "This product includes software developed by Carnegie
#    Mellon University (http://www.speech.cs.cmu.edu/)."
#
# THIS SOFTWARE IS PROVIDED BY CARNEGIE MELLON UNIVERSITY ``AS IS'' AND 
# ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
# NOR ITS EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# ====================================================================

if ($#argv < 1 || $#argv > 2) then
    echo "Usage: $0 <no of states per hmm> (allow skips yes/no)"
    echo "       Default: allow skips yes"
    exit 0
endif
set nstates = $1
if ( $#argv != 2 ) then
  set allowskips = yes
else 
  set allowskips = $2
endif

echo "#"
echo "# ${nstates}-state Bakis topology HMM with non-emitting last state"
echo "# These values are normalized so that rows sum to one."
echo "#"
echo "# NO COMMENTS BETWEEN # OF STATES AND TRANSITION MATRIX"
echo "#"
echo "#"
echo "#Version number"
echo "0.1"
echo "# Number of states per model followed by transition matrix"

@ no = $nstates + 1
echo $no

set n = 1
while ($n <= $nstates)
    set j = 1
    if ( $allowskips == no ) then 
@     nnn = $n + 1
    else 
@     nnn = $n + 2
    endif

    while ($j <= $no)
        if ($j < $n || $j > $nnn) then
            echo -n "0.0	"
@	    j = $j + 1
        else
            echo -n "1.0	"
@	    j = $j + 1
        endif
    end
    echo ""
@   n = $n + 1
end
echo "# Last state has no outgoing arcs unless"
echo "# embedded in a sentence hmm structure"
