#!/bin/csh -f
# ====================================================================
# Copyright (c) 2000 Carnegie Mellon University.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer. 
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# 3. The names "Sphinx" and "Carnegie Mellon" must not be used to
#    endorse or promote products derived from this software without
#    prior written permission. To obtain permission, contact 
#    sphinx@cs.cmu.edu.
#
# 4. Products derived from this software may not be called "Sphinx"
#    nor may "Sphinx" appear in their names without prior written
#    permission of Carnegie Mellon University. To obtain permission,
#    contact sphinx@cs.cmu.edu.
#
# 5. Redistributions of any form whatsoever must retain the following
#    acknowledgment:
#    "This product includes software developed by Carnegie
#    Mellon University (http://www.speech.cs.cmu.edu/)."
#
# THIS SOFTWARE IS PROVIDED BY CARNEGIE MELLON UNIVERSITY ``AS IS'' AND 
# ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
# NOR ITS EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# ====================================================================
#
# NOTE:
# The mdeffile input argument should be built from recognition dictionary
#

set echo

set s3mdef = ./model_architecture/time.6000.mdef
set s2dir = ./sphinx_2_models

set contdir = ./model_parameters/time.cd_semi_6000_delinterp

set s3mixw = $contdir/mixture_weights
set s3mean = $contdir/means
set s3var = $contdir/variances
set s3tmat = $contdir/transition_matrices


###########################################################
# Create s2dir if it doesn't exist

if (! -e $s2dir) mkdir -p $s2dir


###########################################################
# make s2 codebooks

unset echo
echo ""
echo "----------------- Make codebooks -----------------"
echo ""
set echo

bin/mk_s2cb \
    -meanfn $s3mean \
    -varfn  $s3var \
    -cbdir  $s2dir \
    -varfloor 0.00001


###########################################################
# make s2 mixing weights

unset echo
echo ""
echo "----------------- Make chmm files -----------------"
echo ""
set echo

bin/mk_s2hmm \
    -moddeffn $s3mdef \
    -mixwfn   $s3mixw \
    -tmatfn   $s3tmat \
    -hmmdir   $s2dir

###########################################################
# make s2 mixing weights sendump file

unset echo
echo ""
echo "----------------- Make sendump file -----------------"
echo ""
set echo

bin/mk_s2seno s2_4x $s3mdef .semi. $s3mixw 0.0000001 $s2dir/sendump
rm $s2dir/*.ccode $s2dir/*.d2code $s2dir/*.p3code $s2dir/*.xcode

###########################################################
# make s2 phone and map files

unset echo
echo ""
echo "----------------- Make phone and map files -----------------"
echo "**** ASSUMING $s3mdef IS BUILT FOR THE RECOGNITION DICTIONARY ****"
echo ""
set echo

set tmpf = tmp.$$
grep -v "^#" $s3mdef | awk 'NF==12 {print $1,$2,$3,$4}' > $tmpf
bin/mk_s2phone -s2phonefn $s2dir/phone -phonelstfn $tmpf

rm $tmpf

unset echo
echo "----------------- DONE -----------------"
