#!/bin/sh
# ====================================================================
# Copyright (c) 2000 Carnegie Mellon University.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer. 
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# This work was supported in part by funding from the Defense Advanced 
# Research Projects Agency and the National Science Foundation of the 
# United States of America, and the CMU Sphinx Speech Consortium.
#
# THIS SOFTWARE IS PROVIDED BY CARNEGIE MELLON UNIVERSITY ``AS IS'' AND 
# ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
# NOR ITS EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# ====================================================================
#
#  Set up script
#  (with apologies to lenzo re the language)
#
# ====================================================================

if [ ! "$SPHINXTRAINDIR" ]
then
   echo "environment variable SPHINXTRAINDIR is unset"
   echo "set it to your local SphinxTrain directory e.g."
   echo '   bash$ export SPHINXTRAINDIR=/home/awb/projects/SphinxTrain/'
   echo or
   echo '   csh% setenv SPHINXTRAINDIR /home/awb/projects/SphinxTrain/'
   exit 1
fi

if [ $# != 1 ]
then
    echo "Build dirs, and setup scripts for traing Sphinx acoustic models "
    echo "Usage: setup_SphinxTrain DBNAME"
    echo "DBNAME short name for this training set"
    exit 1
fi

DBNAME=$1

if [ "0" != `ls | wc -l` ]
then
   echo "I'm going to make a whole bunch of new directories in"
   echo "    "`pwd`
   echo "This directory is currently non-empty, are you sure this is "
   echo "the directory you want these new directories built in?"
   echo -n "Answer y/n? "
   read answer
   if [ "$answer" != "y" ]
   then
       echo "setup aborted"
       exit -1
   fi
fi

echo Making basic directory structure
mkdir bin
mkdir etc
mkdir feat
mkdir wav

mkdir logdir
mkdir bwaccumdir
mkdir model_parameters
mkdir model_architecture

# have to find these somewhere
mkdir gifs
cp -p $SPHINXTRAINDIR/etc/images/green-ball.gif gifs
cp -p $SPHINXTRAINDIR/etc/images/red-ball.gif gifs

PLATFORM=`grep PLATFORM $SPHINXTRAINDIR/config/system.mak | awk '{print $3}'`

ln -s $SPHINXTRAINDIR/bin.$PLATFORM/* bin
mkdir scripts_pl
cp -pr $SPHINXTRAINDIR/bin.$PLATFORM/scripts_pl/0* scripts_pl
cp -pr $SPHINXTRAINDIR/bin.$PLATFORM/scripts_pl/mc scripts_pl
cp -p $SPHINXTRAINDIR/scripts_pl/maketopology.pl bin
cp -p $SPHINXTRAINDIR/scripts_pl/make_feats bin
cp -p $SPHINXTRAINDIR/scripts_pl/make_dict bin

echo Generating SphinxTrain specific scripts and config file
cat $SPHINXTRAINDIR/etc/sphinx_train.cfg |
  sed 's%___DB_NAME___%'$DBNAME'%g' |
  sed 's%___BASE_DIR___%'`pwd`'%g' |
  sed 's%___SPHINXTRAIN_DIR___%'$SPHINXTRAINDIR'%g' >etc/sphinx_train.cfg

echo "Set up for acoustic training for "$DBNAME" complete"






