# ====================================================================
# Copyright (c) 2000 Carnegie Mellon University.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer. 
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# 3. The names "Sphinx" and "Carnegie Mellon" must not be used to
#    endorse or promote products derived from this software without
#    prior written permission. To obtain permission, contact 
#    sphinx@cs.cmu.edu.
#
# 4. Products derived from this software may not be called "Sphinx"
#    nor may "Sphinx" appear in their names without prior written
#    permission of Carnegie Mellon University. To obtain permission,
#    contact sphinx@cs.cmu.edu.
#
# 5. Redistributions of any form whatsoever must retain the following
#    acknowledgment:
#    "This product includes software developed by Carnegie
#    Mellon University (http://www.speech.cs.cmu.edu/)."
#
# THIS SOFTWARE IS PROVIDED BY CARNEGIE MELLON UNIVERSITY ``AS IS'' AND 
# ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
# NOR ITS EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# ====================================================================
#
#  Sphinx3 include files
#
# ====================================================================
TOP=../..
DIRNAME=include/s3
BUILD_DIRS = 
ALL_DIRS= 
H=  \
  acmod_set.h acmod_set_ds.h agc.h agc_emax.h agc_max.h array_io.h \
  bcomment_io.h best_q.h bo_magic.h bquest_io.h btree.h cep_manip.h \
  ck_seg.h ckd_alloc.h cmd_ln.h cmn.h common.h corpus.h \
  cvt2triphone.h div.h dtree.h enum_subset.h err.h feat.h \
  fgets_wo_nl.h floatbuf_io.h fp_cache.h fread_retry.h gauden.h gauden_io.h \
  get_cpu_time.h get_host_name.h get_time.h hash.h heap.h int32_io.h \
  intbuf_io.h itree.h kmeans.h lambda_io.h lexicon.h* list.h \
  live_norm.h matrix.h merge_den.h metric.h mixw_param_io.h mk_phone_list.h \
  mk_phone_seq.h mk_sseq.h mk_trans_seq.h mk_ts2ci.h mk_wordlist.h mllr.h \
  mllr_class_io.h mllr_io.h model_def.h model_def_io.h model_inventory.h \
  n_words.h norm.h prefetch.h prefix_upto.h prim_type.h profile.h pset_io.h \
  quest.h r_agc_noise.h read_line.h read_seno_dtree.h regmat_io.h remap.h \
  s2_mixing_weights.h s2_param.h s2_read_cb.h s2_read_map.h s2_read_seno.h \
  s2_read_tmat.h s2_write_cb.h s2_write_hmm.h s2_write_seno.h s2io.h s3.h \
  s3_open.h s3cb2mllr_io.h s3gau_io.h s3io.h s3lamb_io.h s3map_io.h \
  s3mixw_io.h s3regmat_io.h s3tmat_io.h s3ts2cb_io.h segdmp.h silcomp.h \
  state.h state_param_def_io.h state_seq.h swap.h tmat_param_io.h topo_read.h \
  ts2cb.h two_class.h uttfile.h vector.h was_added.h \
  array_alloc.h timer.h

FILES = Makefile $(H)

ALL = 

include $(TOP)/config/common_make_rules

